### ISSUE TITLE
[BUG] Memory overflow when lora fine-tuning meta-llama/Meta-Llama-3.1-8B-Instruct

### ISSUE THREAD

**Issue by hschaeufler** [ml-explore/mlx#1406]
**Describe the bug**
When finetuning a Llama 3.1 Instruct LLM, the memory consumption increases from 90 GB to over 200 GB after approx. 60 iterations. Because of this my M3 Max Macbook with 128GB memory crashes. Below is my config and the command. I cannot provide the data set itself as it contains sensitive data. But below is an example.

![image](https://github.com/user-attachments/assets/a2a3a5c3-c8e3-479f-8aca-538a02a4206b)

**To Reproduce**
Code Snippet:
```python
mlx_lm.lora --config "fine_tuning/lora_config.yaml"
```

```yaml
model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
train: true
data: "fine_tuning/"
seed: 0
lora_layers: 16
batch_size: 4
iters: 2573
val_batches: 25
learning_rate: 1e-5
steps_per_report: 10
steps_per_eval: 200
resume_adapter_file: null
adapter_path: "adapters"
save_every: 100
test: false
test_batches: 100
max_seq_length: 8192
grad_checkpoint: false
use_dora: false
lora_parameters:
  keys: ["self_attn.q_proj", "self_attn.v_proj"]
  scale: 0.5
  rank: 16
  dropout: 0.05
lr_schedule:
  name: cosine_decay
  warmup: 60
  arguments: [1e-5, 62, 0] # passed to scheduler
```

Structure of train.jsonl and valid.jsonl (each line contains code from one class to test and one unit test)
```json
{"text":"### Code: import 'package:app\/features\/example\/domain\/entities\/entity.dart';\n... ### Test: import 'package:flutter_test\/flutter_test.dart';\n\nvoid main() {\n}\n"}
{"text":"### Code: import 'package:app\/features\/example\/domain\/entities\/entity.dart';\n... ### Test: import 'package:flutter_test\/flutter_test.dart';\n\nvoid main() {\n}\n"}
```

train.jsonl has 2058 records and valid.jsonl 257.

**Expected behavior**
Constant memory usage.

**Desktop (please complete the following information):**
 - OS Version: Version 14.6.1 (23G93)
 - MLX-LLM-Version: 0.18.1
 - Version: Mac15,9 with Apple M3 Max and 128GB Working Memory

**Additional context**
Found this: https://github.com/ml-explore/mlx-examples/issues/738 but memory checkpointing is deactivated.
