### ISSUE TITLE
[BUG] ERROR: No matching distribution found for mlx>=0.x

### ISSUE THREAD

**Issue by Blaizzy** [ml-explore/mlx#1536]
**Describe the bug**
My GH tests are failing because they can't install mlx.

**To Reproduce**
Workflow yaml:
```yaml
name: Test PRs

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: macos-14

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          run: |
            brew install python@3.10
            python3 -m venv env
            source env/bin/activate


        - name: Run style checks
          run: |
            pip install pre-commit
            pre-commit run --all
            if ! git diff --quiet; then echo 'Style checks failed, please install pre-commit and run pre-commit run --all and push the change'; exit 1; fi

        - name: Install dependencies
          run: |
            pip install pytest
            pip install -e .

        - name: Run Python tests
          run: |
            cd mlx_vlm/
            pytest -s ./tests
```

Requirements.txt: 
```txt
mlx>=0.18.1 
```

**Expected behavior**
I expect the dependencies to install normally as in the past.

**Desktop (please complete the following information):**
 - OS Version: MacOS 14 

**Additional context**
